TestCntlrApp/src/enbApp/nb_enb_db.h, TestCntlrApp/src/tfwApp/fw_api_int.h
Title: Modified code to support 32 eNBs 
Summary: Code is modified for testing more eNB and UEs.
The new test case is added in PR, https://github.com/facebookincubator/magma/pull/1077
Newly added tests:
test_multi_enb.py
=> Increased number of eNBs to 32 for multi enb testing

TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/tfwApp/fw_uemsg_handler.c, TestCntlrApp/src/ueApp/ue_app.c
Bug fix to send valid PTI in ESM information response message
ESM information response was sent with wrong Procedure Transaction Identity(PTI) due to which MME was sending STATUS message with cause "invalid PTI". This PR fixes the bug
1.Executed S1 SIM sanity
2.Executed test_attach_esm_information.py and test_attach_esm_information_wrong_apn.py TCs
=> [Bug fix]Bug fix for changing assertTrue to assertEqual

TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb.h, TestCntlrApp/src/enbApp/nb_ue_msg_hndlr.c, TestCntlrApp/src/fw_cm/nbt.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x
Provided fix for 3 digit and 2 digit PLMN
Full description of the PR.
1. Correcting the serving plmn updation in ueCb which was eventually used in Kasme calculation
2. In order to identify the 5 digit pLMN or 6 digit PLMN, previously "0" was used as differentiator, if plmn[5] is zero, that was regarded as 5 digit PLMN, which is incorrect as "0" is also valid PLMN  digit.
To differentiate 5 digit PLMN or 6 digit PLMN, plmn length is passed from test cases
Todo:
Need to test multiple eNB each configured with different PLMN sizes
- Executed 3 digit PLMN and 2 digit PLMN for single and multiple eNB
- Executed s1ap sanity test suite
=> Rsarwad fix for plmn length

TestCntlrApp/src/enbApp/nb.h, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/enbApp/nb_ue_msg_hndlr.c, TestCntlrApp/src/fw_cm/nbu.c, TestCntlrApp/src/fw_cm/nbu.x, TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.h, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/tfwApp/fw_uemsg_handler.c, TestCntlrApp/src/ueApp/ue_app.c
Modified code to handle E_Rab_Setup_Request received with QCI, 0 and provide an indication to test stub that erab_setup_req is failed for list of bearers
Modified code to handle E_Rab_Setup_Request received with QCI, 0 
On reception of E_Rab_Setup_request with QCI,0. enbApp shall send an indication to tfwapp to indicate that eNB app is failed to establish bearers 
Tfwapp shall forward the indication to test stub. The test stub displays the received message with bearer-id 
- Executed s1ap sanity test suite
-Added new test case, test_attach_detach_dedicated_qci_0.py
=> Modified code to handle E_Rab_Setup_Request received with QCI, 0 

TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb.h, TestCntlrApp/src/enbApp/nb_dam.c, TestCntlrApp/src/enbApp/nb_dam.h, TestCntlrApp/src/enbApp/nb_ifm_dam.h, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/enbApp/nb_ue_msg_hndlr.c, TestCntlrApp/src/fw_cm/nbu.x, TestCntlrApp/src/fw_cm/tft.h, TestCntlrApp/src/ueApp/ue_app.c, TestCntlrApp/src/ueApp/ue_li.c
Added UL TFT support in S1 SIM
Added code to store the UL TFT packet filter/s in the order of precedence and send the UL IP packet on the dedicated bearer if the packet filter matches. If not the packet is sent on default bearer.
- Executed test_attach_detach_rar_tcp_data.py test case from PR #1442
=> [enhancement] UL TFT support in S1 SIM

TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/ueApp/ue_app.c
P-CSCF support in S1 SIM
Added P-CSCF IPv4 and IPv6 address support
Test Plan:
1.	Verified S1 SIM sanity
2.	Executed 2 new TCs: test_attach_detach_with_pcscf_address.py and 
test_attach_detach_secondary_pdn_with_pcscf_address.py PR - #1577
=> S1sim pcscf address support

TestCntlrApp/src/tfwApp/fw_uemsg_handler.c, TestCntlrApp/src/ueApp/ue_app.c
Fixed printing of ue id multiple times
This PR has the following fixes:
1. Ue Id was getting printed multiple times after receiving PDN Connection/Disconnection response as there were duplicate entries of the ue id in the ueIdList maintained at fwCb. Added a fix to clear the ue entry after processing the response
2. Old fix for CM_ESM_MAX_BEARER_ID supported was overwritten during one of the merges. Added the fix back.
1. Verified S1 SIM sanity
2. Verified test_attach_detach_secondary_pdn_with_pcscf_address.py and test_attach_detach_with_pcscf_address.py TCs
=> [Bug fix] Fixed printing of ue id multiple times

README.md
Added guide note in README.md file for allocation of large number of UE IP addresses
While using S1APTester with Magma, the attach for more than 243 UEs is failing. The reason for the failure is that the configuration parameters in Magma have one hard-coded TEST_IP_BLOCK with a restricted number of allowed IP addresses. This PR adds the steps in Readme file, which needs to be followed to modify configuration in Magma, in order to allocate more than 243 UE IP addresses, along with some examples.
=> [Enhancement] [Help] [UE_IP_Address_Allocation] Added guide note in README.md file for allocation of large number of UE IP addresses

TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.h, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/ueApp/ue_app.c
Title
Support to send Authentication Failure message from s1ap simulator
Summary
Support to handle Authentication Failure message from python test script and sends message from s1aptester(UE) to MME.
-Background:
As part of Magma issue PR#1022 identified that MME crashes when UE Authentication failure message received at MME. To simulate the scenario, added python test script at magma AGW and observed that there was no support to send the Authentication failure message from S1APTester. Hence added support to handle authentication failure message from python test script and sending to MME.
Test plan
Build sanity
Newly added tests - test_attach_auth_failure.py
=> Changed code to send Authentication Failure message from test stub

TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrStub/src/ts_utls.c
Reverts facebookexperimental/S1APTester#22
The code compilation is failing with these changes, so reverting this commit.
=> Revert "resolved compilation error of Test Controller Stub"

TestCntlrStub/src/ts_utls.c
Resolved compilation error in TestCntlrStub
Current master code does not compile for TestCntlrStub:
`
../src/ts_utls.c:381:10: error: 'tfwPdnDisconnFail' undeclared (first use in this function);
../src/ts_utls.c:1766:26: error: 'ResetReq {aka struct _resetReq}' has no member named 'u'
../src/ts_utls.c:1767:26: error: 'ResetReq {aka struct _resetReq}' has no member named 'u'
../src/ts_utls.c:1768:33: error: 'ResetReq {aka struct _resetReq}' has no member named 'u'
../src/ts_utls.c:1771:31: error: 'ResetReq {aka struct _resetReq}' has no member named 'u'
`
Modified TestCntlrStub/src/ts_utls.c to be able to compile.
=> Fix Compilation error.

TestCntlrApp/src/enbApp/nb_ue_msg_hndlr.c, TestCntlrApp/src/ueApp/ue_app.c, TestCntlrApp/src/ueApp/ue_li.c
When UE's ECM state changes from Idle to connected,  s1ap tester was not forwarding UL data, due to which test_paging_request.py testcase was failing.
When UE's ECM state changes from Idle to connected,  s1ap tester was not forwarding UL data,  Because when UE was moved to Idle state, UE's DRB contexts were deleted which shouldn't have been deleted. DRBs should be deleted only when UE processes through detach procedure
So as part of this PR, UE's DRB contexts are not deleted when goes to Idle mode, instead DRB contexts are deleted as part of detach procedure
- Sanity test suite is working fine
- Existing relevant tests are test_paging_request.py, downlink and uplink data testcases
=> Provided fix for test case, test_paging_request.py

TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/fw_cm/nbt.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x
Signed-off-by: rashmi <rashmi.sarwad@radisys.com>
Full description of the PR.
- Added provision to send enb_ue_s1ap_id and mme_ue_s1ap_id from test script while testing Partial Reset message. So that we can simulate the scenario to send Partial Reset message with unknown s1ap_ids from test script.
- Sanity test suite is working fine
- Added new test-case, test_enb_partial_reset_with_unknown_ue_s1ap_ids.py
=> Added code to provide enb_ue_s1ap_id and mme_ue_s1ap_id from test script

TestCntlrApp/src/enbApp/nb_dam.c
Fixed multi UE data test case failure issue
The multi UE data test cases were failing and getting stuck for some random UE. This PR fixes one part of the issue where it was corrupting the key to be used for fetching the pdnCb from ueCb.
Verified with Sanity and multiple runs of multi UE data test cases.
=> [Bug_Fix] [Data_Testing] Fixed multi UE data test case failure issue

TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/ueApp/ue_app.c, TestCntlrApp/src/ueApp/ue_app_sec.c, TestCntlrApp/src/ueApp/ue_app_sec.x
…value
Signed-off-by: Pruthvi Hebbani <pruthvi.hebbani@radisys.com>
[new scenario] Simulate sending of service req with zero mac
This PR contains code changes to send service request message with mac value as 0. MME does not find the UE context after receiving this message and triggers service reject with cause "UE context not found"
- Verified TC in magma PR - https://github.com/magma/magma/pull/3924
=> [new scenario] Simulate sending of service req with zero mac value

TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb.h, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/enbApp/nb_tmr.c, TestCntlrApp/src/enbApp/nb_ui.c, TestCntlrApp/src/fw_cm/nbt.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x
[new scenario] Out of order erab setup rsp
This PR supports sending of erab setup rsp out-of-order i.e after activate default/dedicated eps bearer accept NAS message is sent
- Verified new TCs in magma PR #3817
=> [new scenario] Out of order erab setup rsp

TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/enbApp/nb_tmr.c
[Bug_Fix] [Stateless_Testing] Fixed issues with nw initiated detach not handled for stateless ics drop test cases
The NW Initiated detach requests were getting dropped for test case "s1aptests/test_attach_ics_drop_with_mme_restart.py". The reason was that the ICS req dropped flag was not getting reset from test script and hence for any new DL request, the message was getting dropped. This PR fixes the issue.
Verified with Sanity and individual test case executions
=> [Bug_Fix] [Stateless_Testing] Fixed issues with NW initiated detach not handled for stateless ics drop test cases

TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.h, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/tfwApp/fw_uemsg_handler.c, TestCntlrApp/src/ueApp/ueAppdbm.x, TestCntlrApp/src/ueApp/ue_app.c, TestCntlrApp/src/ueApp/ue_emm_edm.c
[s1 sim][new feature] IMEI restriction support
This PR has the following support:
1.	Support to send imeisv in security mode complete and identity rsp messages
2.	Support to include imeisv value from the test script in security mode complete and identity rsp message
- Verified new TCs test_imei_restriction_smc.py and test_imei_restriction_no_imeisv_in_smc.py
=> [s1 sim][new feature] IMEI restriction support

TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb.h, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/enbApp/nb_ui.c, TestCntlrApp/src/fw_cm/nbt.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x
[error_ind_support] support to drop erab setup request
This PR has support to drop erab-setup-request message received from mme in order to simulate sending of error indication message
- Tested test_send_error_ind_for_dl_nas_with_auth_req.py and test_send_error_ind_for_erab_setup_req.py in magma PR https://github.com/magma/magma/pull/6338
=> [error_ind_support] support to drop erab setup request

TestCntlrApp/src/tfwApp/fw_api_int.h
[s1sim][lte] Macros for esm cause values
Added macros for missing esm cause which are used in s1sim TCs to verify if a reject message is received with appropriate cause values
- Verified TCs updated in magma PR https://github.com/magma/magma/pull/6407
=> [s1sim][lte] Add macros for esm cause values

TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/ueApp/ueAppdbm.x, TestCntlrApp/src/ueApp/ue_app.c
Added code to drop activate default bearer context request
As part secondary PDN connection, mme sends activate default eps bearer context request and starts 3485 timer. 
On 3485 timer expiry, mme re-transmits activate default eps bearer context request. 
At s1ap, on reception of activate default eps bearer context request, s1ap sends activate default eps bearer context accept.
But now we intend to test 3485 timer expiry with mme restart, in which case s1ap should not send the response message. 
Later after mme has recovered, mme re-trasmits the activate default eps bearer context request for which s1ap has to respond.
To guard whether s1ap should send activate default eps bearer context accept message or not, I added code to send an indication from TFW to indicate that s1ap should not …
=> Added code to drop activate default bearer context request

TestCntlrApp/src/tfwApp/fw_uemsg_handler.c
Signed-off-by: Pruthvi Hebbani <pruthvi.hebbani@radisys.com>
[bug fix] Fix for sending concurrent standalone PDN session requests
S1ap tester was crashing when concurrent PDN session requests were triggered because it was deleting all the pending timerCbs stored in the UeCb after receiving the 1st response. This PR fixes the issue.
- Verified PDN sessions are successfully created by sending concurrent standalone PDN connectivity requests
=> [bug fix] Fix for sending concurrent standalone PDN session requests

TestCntlrApp/src/fw_cm/uet.x, TestCntlrApp/src/tfwApp/fw_api_int.c, TestCntlrApp/src/tfwApp/fw_api_int.x, TestCntlrApp/src/ueApp/ue_app.c
Support to configure GUTI from test script
This PR supports configuration of GUTI value from the test script. 
ueApp reads GUTI provided from the test script if available. Otherwise it reads the value stored in ueContext.
- Verified new TC in PR- https://github.com/magma/magma/pull/7918
- Verified complete sanity suite
=> Support to configure GUTI from testscript

TestCntlrApp/src/ueApp/ue_app.c
Corrected S1AP message name in S1APTester log
EMM Information indication was wrongly marked as detach accept message, giving false impression of detach procedure. This PR corrects the message name to be printed in the log.
Verified with sanity and individual test cases
=> fix(agw): Corrected message name in log

TestCntlrApp/src/cm/szt.x, TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb.h, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/s1ap/sz.x, TestCntlrApp/src/s1ap/sz_mgmt.c, TestCntlrApp/src/s1ap/sz_ui.c
Signed-off-by: Rashmi <rashmi.sarwad@radisys.com>
Modified code to release the UE for which eNB reset message is triggered
As part of fixing issue, https://github.com/magma/magma/issues/11050.  test case, test_multi_enb_complete_reset.py was failing because as part of test case, it first connects 5 eNBs and for each eNB there shall be one UE connected. 
When complete reset is initiated for one eNB; all UE contexts were getting deleted; Ideally we need to delete the contexts only for the UE for which eNB Reset is triggered. 
This issue is fixed in this PR
Executed s1ap sanity test suite
=> Modified code to release the UE for which eNB reset message is triggered

TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c
Fix  ipv4v6 transport layer addresses handling in ICS Req and ERAB SETUP Req
S1ap tester does not handle ipv4v6 transport layer addresses received in ICS request or ERAB SETUP request as of now. Fixed the issue temporarily by replacing RFAILED with break.
- Verified UE successfully attaches to the network by executing test_attach_detach.py TC on PR: https://github.com/magma/magma/pull/10613/
=> Fix  ipv4v6 transport layer addresses handling in ICS Req and ERAB SETUP Req

TestCntlrApp/src/enbApp/nb.c, TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c, TestCntlrApp/src/tfwApp/fw_api_int.c
Signed-off-by: Josiah White <me@josiahwhite.io>
Properly parse PLMN and respect suppTA passed by user
- Truncates the size of the PLMN id as returned by `strlen`
- Removes ifdefs in the `suppTA` parameter handling to allow the user-specified TA to be sent in the S1-Setup request
- Changed some string copies from `strcpy` to `strncpy` with a size limit.
Verified with sanity
=> Properly parse PLMN and respect suppTA passed by user

TestCntlrApp/src/cm/cm_os.c, TestCntlrApp/src/fw_cm/cm_os.c
Signed-off-by: Marco Pfirrmann <marco.pfirrmann@tngtech.com>
PR removes the c++-lib stropts.h 
`stropts.h` is a c++ library that is not supported anymore by current linux distributions. This creates a problem i.e. for upgrading the magma_test vm to Ubuntu 20.04, see magma/magma#4519
Upon first code review and testing, this lib is apparently not needed for the integration tests. Can we drop it? 
- S1AP Integration tests for magma
The results for both `make -i precommit` and `make -i integ_test` in magma are identical with and without the change.
=> stropts.h is no longer included
